language: node_js
node_js:
  - "9"
before_script:
  - npm install
script:
  - npm run build
  - cp dist/index.html dist/404.html
deploy:
  local-dir: dist
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master
notifications:
  email:
    on_success: never
    on_failure: always
  slack: diginamic:nIQwPkWk2zfq2fjtzxMWhuBD#travis